### ISSUE TITLE
"call of Value.Invoke on undefined"

### ISSUE THREAD

**Issue by azer** [mattn/golang-wasm-example#3]
Hey there,

I've compiled the example with the development version of Go and got the error mentioned in the title when I tried to open the example in the browser.

Go version: 
```
go version devel +1b870077c8 Fri Aug 3 17:21:10 2018 +0000 linux/amd64
```

The console output:

```
goroutine 1 [running]:
wasm_exec.js:45 syscall/js.Value.Invoke(0x7ff8000000000001, 0xc0757e0, 0x3, 0x3, 0xc02e2a0)
wasm_exec.js:45 	/usr/lib/go/src/syscall/js/js.go:281 +0x31
wasm_exec.js:45 syscall/js.NewCallback(0xc00a2c0, 0xc00a2c0, 0xc02e2a0)
wasm_exec.js:45 	/usr/lib/go/src/syscall/js/callback.go:49 +0xc
wasm_exec.js:45 net/http.(*Transport).RoundTrip(0x320b60, 0xc0ae000, 0x0, 0x0, 0x0)
wasm_exec.js:45 	/usr/lib/go/src/net/http/roundtrip_js.go:72 +0x2f
wasm_exec.js:45 net/http.send(0xc0ae000, 0xae220, 0x320b60, 0x0, 0x0, 0x0, 0xc00c050, 0x22, 0xc028bd0, 0x1)
wasm_exec.js:45 	/usr/lib/go/src/net/http/client.go:252 +0x16
wasm_exec.js:45 net/http.(*Client).send(0x32cc60, 0xc0ae000, 0x0, 0x0, 0x0, 0xc00c050, 0x0, 0x1, 0x0)
wasm_exec.js:45 	/usr/lib/go/src/net/http/client.go:176 +0x10
wasm_exec.js:45 net/http.(*Client).do(0x32cc60, 0xc0ae000, 0x0, 0x0, 0x0)
wasm_exec.js:45 	/usr/lib/go/src/net/http/client.go:643 +0x17
wasm_exec.js:45 net/http.(*Client).Do(0x32cc60, 0xc0ae000, 0xc04a1c0, 0x1e, 0x0)
wasm_exec.js:45 	/usr/lib/go/src/net/http/client.go:511 +0x2
wasm_exec.js:45 net/http.(*Client).Get(0x32cc60, 0xc04a1c0, 0x1e, 0xc04a1c0, 0x1e, 0x20)
wasm_exec.js:45 	/usr/lib/go/src/net/http/client.go:400 +0x5
wasm_exec.js:45 net/http.Get(0xc04a1c0, 0x1e, 0x1e, 0x0, 0x0)
wasm_exec.js:45 	/usr/lib/go/src/net/http/client.go:372 +0x2
wasm_exec.js:45 main.main()
wasm_exec.js:45 	/home/azer/code/golang-wasm-example/test.go:22 +0xf
```

Any ideas ? Could it be a platform difference ? or am I possibly messing up something in my system ?

**Comment by sunfmin** [comment]
I am having the same:

```
url =  http://localhost:5000/logo.png
wasm_exec.js:45 panic: syscall/js: call of Value.Invoke on undefined
wasm_exec.js:45 
wasm_exec.js:45 goroutine 1 [running]:
wasm_exec.js:45 syscall/js.Value.Invoke(0x7ff8000000000001, 0xc077740, 0x3, 0x3, 0xc02e2a0)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/syscall/js/js.go:298 +0x31
wasm_exec.js:45 syscall/js.NewCallback(0xc00a300, 0xc00a300, 0xc02e2a0)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/syscall/js/callback.go:49 +0xc
wasm_exec.js:45 net/http.(*Transport).RoundTrip(0x322b60, 0xc0b2000, 0x0, 0x0, 0x0)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/net/http/roundtrip_js.go:96 +0x33
wasm_exec.js:45 net/http.send(0xc0b2000, 0xae640, 0x322b60, 0x0, 0x0, 0x0, 0xc00c058, 0x22, 0xc028bd0, 0x1)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/net/http/client.go:250 +0x16
wasm_exec.js:45 net/http.(*Client).send(0x32ec60, 0xc0b2000, 0x0, 0x0, 0x0, 0xc00c058, 0x0, 0x1, 0x0)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/net/http/client.go:174 +0x10
wasm_exec.js:45 net/http.(*Client).do(0x32ec60, 0xc0b2000, 0x0, 0x0, 0x0)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/net/http/client.go:641 +0x17
wasm_exec.js:45 net/http.(*Client).Do(0x32ec60, 0xc0b2000, 0xc04c220, 0x1e, 0x0)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/net/http/client.go:509 +0x2
wasm_exec.js:45 net/http.(*Client).Get(0x32ec60, 0xc04c220, 0x1e, 0xc04c220, 0x1e, 0x20)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/net/http/client.go:398 +0x5
wasm_exec.js:45 net/http.Get(0xc04c220, 0x1e, 0x1e, 0x26, 0x0)
wasm_exec.js:45 	/usr/local/Cellar/go/1.11/libexec/src/net/http/client.go:370 +0x2
wasm_exec.js:45 main.main()
wasm_exec.js:45 	/Users/sunfmin/go/src/github.com/mattn/golang-wasm-example/test.go:25 +0x12
```
